// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:7428ef24-f5c4-4203-9344-27631a724c31',
    'aws_cognito_region': 'eu-west-1',
    'aws_mobile_analytics_app_id': '89b683ce9bb449a082121e56f82b8612',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'be0689cc-b1ed-4e99-9706-b86f2abee788',
    'aws_project_name': 'HY',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'hy-mobilehub-909513043',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-1_R8jMDNbWG',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2l1u40k2mdqgpcuc6fnjo23i86',
}

export default awsmobile;

