// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ccf9afd3-71f2-4cb6-9ba8-3d1003df837c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_O0UvhBdhj",
    "aws_user_pools_web_client_id": "29q05h4nrru5sui7q9dk4vopm7"
};


export default awsmobile;
