// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:85d4e06b-975c-4cca-a744-ab77a00f8048",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XLIPEnFDb",
    "aws_user_pools_web_client_id": "j8b8ke4dovt0b97mlhv2cg06c",
    "oauth": {},
    "aws_user_files_s3_bucket": "hyapp-bucket0190940-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
